name: sirsak_pop_nasabah
description: Sirsak Point of Purchase app for nasabah
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.2.3
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^14.2.7
  intl: ^0.20.2
  json_annotation: ^4.8.1
  logger: ^2.6.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_lint: ^2.3.13
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/League_Spartan/LeagueSpartan-VariableFont_wght.ttf

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic

    - family: GochiHand
      fonts:
        - asset: assets/fonts/Gochi_Hand/GochiHand-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
  fonts:
    enabled: true
