name: sirsak_pop_nasabah
description: Sirsak Point of Purchase app for nasabah
publish_to: 'none'
version: 0.1.5+10

environment:
  sdk: '>=3.10.0'

dependencies:
  crypto: ^3.0.7
  dio: ^5.7.0
  encrypt: ^5.0.3
  external_app_launcher: ^4.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_riverpod: ^3.1.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  geolocator: ^13.0.2
  go_router: ^17.0.1
  hooks_riverpod: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  logger: ^2.6.2
  mobile_scanner: ^6.0.3
  package_info_plus: ^8.0.0
  permission_handler: ^12.0.1
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^4.0.0
  sentry_flutter: ^9.10.0
  toastification: ^3.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.0+1
  riverpod_lint: ^3.1.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
          style: italic

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/League_Spartan/LeagueSpartan-VariableFont_wght.ttf

    - family: NunitoSans
      fonts:
        - asset: assets/fonts/Nunito_Sans/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/Nunito_Sans/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic

    - family: GochiHand
      fonts:
        - asset: assets/fonts/Gochi_Hand/GochiHand-Regular.ttf

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
    rive: false
    lottie: false
  fonts:
    enabled: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/sirsak_logo_transparent.png"
  adaptive_icon_background: "#325B0C"
  adaptive_icon_foreground: "assets/images/sirsak_logo_transparent.png"
